env:
  browser: true
  es2021: true
  node: true
extends: 
  - eslint:recommended
  - plugin:vue/recommended
  - plugin:prettier-vue/recommended
  - prettier
plugins:
  - prettier-vue
parserOptions:
  ecmaVersion: 13
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  vue/max-len:
    - error
    - 120
globals:
  process: true